services:
  mobile-voting:
    build: .
    container_name: mobile-voting
    restart: unless-stopped
    environment:
      - DATA_DIR=/data
    expose:
      - "3000"
    networks:
      - build_default
    volumes:
      - ../data:/app/data

networks:
  build_default:
    external: true
