apiVersion: v2
name: mes-services
description: MES Platform — all domain microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - mes
  - manufacturing
  - isa-95
  - event-sourcing
maintainers:
  - name: MES Platform Team
    email: mes-platform@example.com
dependencies:
  - name: postgresql
    version: "^15.0"
    repository: https://charts.bitnami.com/bitnami
    alias: postgresql
    condition: postgresql.enabled
