apiVersion: v1
kind: ConfigMap
metadata:
  name: mes-common-config
  namespace: mes-platform
data:
  KAFKA_BROKERS: "kafka-headless.kafka.svc.cluster.local:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry.kafka.svc.cluster.local:8081"
  KEYCLOAK_URL: "http://keycloak.auth.svc.cluster.local:8080"
  KEYCLOAK_REALM: "mes"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4317"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
